# Generated by Django 6.0.1 on 2026-01-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form_data',
            new_name='user_data',
        ),
    ]
