# Generated by Django 6.0.1 on 2026-01-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('name', models.CharField(default='Anonymous', max_length=250)),
                ('institute', models.CharField(default='Anonymous', max_length=250)),
            ],
        ),
    ]
