# Generated by Django 6.0.1 on 2026-01-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='institute',
            field=models.CharField(blank=True, default='Anonymous', max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, default='Anonymous', max_length=250),
        ),
    ]
